apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limitrange
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - max:
      ephemeral-storage: "50Gi"
    min:
      ephemeral-storage: "100Mi"
    default:
      ephemeral-storage: "15Gi"
    defaultRequest:
      ephemeral-storage: "1Gi"
    type: Container
