apiVersion: v1
kind: LimitRange
metadata:
  name: pipeline-limitrange
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - max:
      ephemeral-storage: "20Gi"
    min:
      ephemeral-storage: "1Gi"
    default:
      ephemeral-storage: "15Gi"
    defaultRequest:
      ephemeral-storage: "10Gi"
    type: Container
